8278489: Preserve result in native wrapper with +UseHeavyMonitors
openjdk/jdk18 pull request #16
Opened 2021-12-13 20:54 UTC by rkennke

Testing observed a few failures after JDK-8276901. The reason for the failures is in the native-wrappers, in the +UseHeavyMonitors paths, we don't preserve the result register after the native call.

Testing:
 - [x] java/awt/color, sun/java2d/cmm tests (x86_32, x86_64 x -UseHeavyMonitors, +UseHeavyMonitors)
 - [ ] tier1 (x86_32, x86_64 x -UseHeavyMonitors, +UseHeavyMonitors)

2021-12-13 22:46 UTC, dholmes-ora reviewed
Not a review as not my area but saw some nits with the adjusted code.

David

2021-12-13 22:46 UTC, dholmes-ora commented on src/hotspot/cpu/x86/sharedRuntime_x86_32.cpp
> +    // Must save rax, if if it is live now because cmpxchg must use it
Existing typo: if if

2021-12-13 22:46 UTC, dholmes-ora commented on src/hotspot/cpu/x86/sharedRuntime_x86_32.cpp
> +     }
Indentation looks wrong

2021-12-13 22:46 UTC, dholmes-ora commented on src/hotspot/cpu/x86/sharedRuntime_x86_64.cpp
> +    // Must save rax if if it is live now because cmpxchg must use it
existing typo: if if

2021-12-20 15:29 UTC, shipilev requested changes
The same thing affects `sharedRuntime_aarch64.cpp`, is it not?
Otherwise the change makes sense to me.

2021-12-21 16:08 UTC, rkennke commented
> The same thing affects `sharedRuntime_aarch64.cpp`, is it not? Otherwise the change makes sense to me.

Right. I did the same fix there.

2021-12-21 16:36 UTC, shipilev approved these changes
Looks fine to me, but someone else should take a look too.

2022-01-04 17:41 UTC, vnkozlov approved these changes
Good.

2022-01-10 20:45 UTC, rkennke commented
/integrate

2022-01-10 20:47 UTC, closed without merging